### ISSUE TITLE
Investigate performance regression from Brayns 0.5.0-beta to latest

### ISSUE THREAD

**Issue by straaljager** [BlueBrain/Brayns#341] opened 2018-03-07 12:52 UTC

**Comment by straaljager** [comment] 2018-03-07 12:57
Docker image with 2 GB:
![latest_brayns](https://user-images.githubusercontent.com/13703350/37093376-69f8c0bc-220f-11e8-9132-a11cebf66515.png)
![brayns_0_5_0_beta](https://user-images.githubusercontent.com/13703350/37093378-6c9b0b86-220f-11e8-949d-090a8825c9d0.png)

Docker with 6 GB:
![brayns_latest_15fps](https://user-images.githubusercontent.com/13703350/37093393-7a67dffa-220f-11e8-9845-d034eb818405.png)
![brayns_0_5_0_beta_24fps](https://user-images.githubusercontent.com/13703350/37093398-7fe9835c-220f-11e8-922e-920dfcfea93a.png)

**Comment by tribal-tec** [comment] 2018-03-07 15:35
Hmm, can't reproduce that, even on my poor MacBook Air. I get ~26FPS server side, and ~18FPS client side. How is my inferior machine even faster than yours?

**Comment by rolandjitsu** [comment] 2018-03-07 15:46
@tribal-tec note that @straaljager has Microsoft products running on his machine which are probably already draining memory 😄Skype is also draining memory as far as I remember.

@straaljager could you check your activity monitor and see if something else besides chrome and docker consume a lot of memory/cpu?

**Comment by straaljager** [comment] 2018-03-15 10:18
Just tested again with Brain 0.5.0-beta and latest. The server fps is 29 fps for both, client fps is 22 fps with 0.5.0 beta and doesn't go higher than 13 fps with latest. All else is the same (I closed most applications to save memory)

**Comment by rolandjitsu** [comment] 2018-03-21 08:30
I think that this should be fixed with https://github.com/BlueBrain/Brayns/pull/357. @straaljager could you pull latest from Docker and check how it is now?

**Comment by straaljager** [comment] 2018-03-21 12:52
It definitely feels a lot smoother than before, but the client fps is still hovering around 15 fps, while server fps is 36 fps

**Comment by straaljager** [comment] 2018-03-21 12:54
For reference, Brayns 0.5.0-beta was around 22 fps.

**Comment by rolandjitsu** [comment] 2018-06-07 13:33
Closing this as it is no longer the case with the latest changes.

**Closed by rolandjitsu** 2018-06-07 13:33 UTC
